import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "QuizApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  bg-gray-800/90 h-[100svh]`}>
        <div className="max-w-[700px] bg-gray-800/10 text-center p-12 rounded-lg mx-auto pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
